on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: SFTP Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Enable bundler cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y libmagickwand-dev
        
        
      - name: Install deps
        run: |
          gem update --system
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          npm install -g mermaid.cli

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.IST_USERNAME }}
          server: ${{ secrets.IST_SERVER }}
          port: 22
          local_path: './_site/*'
          remote_path: '/afs/.ist.utl.pt/groups/sency/web/'
          sftp_only: true
          password: ${{ secrets.IST_HOSTING }}
